site_name: Sealand Government Portal
theme:
  name: material
  logo: favicon.png
  favicon: favicon.png
  font:
    text: Manrope
  palette:
    - media: "(prefers-color-scheme: light)" # 

      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: purple
    - media: "(prefers-color-scheme: dark)" # 

      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: purple
  features:
    - navigation.tabs
    - navigation.tabs.sticky
features:
    - navigation.instant
    - navigation.sections
    - navigation.indexes
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
plugins:
  - i18n:
      default_language: en
      languages:
        en: English
        fr: Français

